const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('plantilla_dashboard.html','utf8'),ctx={};vm.createContext(ctx);
vm.runInContext(html.slice(html.indexOf('function distanceStats('),html.indexOf('function renderDistances(')),ctx);
const a={rid:'a',usable:true,disp_km_plan:10000,disp_km_real:12000},b={rid:'b',usable:true,disp_km_plan:5000,disp_km_real:null};
let s=ctx.distanceStats([a,b,a,{rid:'bad',usable:false,disp_km_plan:999999}]);
assert.equal(s.plan,15);assert.equal(s.real,12);assert.equal(s.diff,2);assert.equal(s.pct,20);assert.equal(s.nPair,1);
assert.equal(ctx.distanceStats([]).plan,null);
assert.equal(ctx.distanceStats([{...a,disp_descartada:true}]).diff,null);
assert.equal(ctx.distanceStats([{...a,disp_km_plan:0,disp_km_real:0}]).pct,null);
assert.equal(ctx.distanceStats([{...a,disp_km_real:-1}]).real,null);
console.log('Distances: meters to km, unique routes, paired denominator, missing and anomalous data OK');
assert.equal(ctx.fuelStats({plan:100,real:200,diff:100},1500).costReal,84000.00000000001);
assert(Math.abs(ctx.fuelStats({plan:100,real:200,diff:100},1500).real-56)<1e-9);
assert.equal(ctx.fuelStats({plan:100,real:200,diff:100},null).costReal,null);
assert.equal(ctx.fuelStats({plan:null,real:null,diff:null},1500).real,null);
assert.equal(ctx.fuelStats({plan:100,real:200,diff:100},0).costReal,0);
console.log('Fuel: fixed 28 L/100 km, entered price, missing values and zero price OK');
ctx.cleanPersona=s=>s.toUpperCase().replace(/ RECARGA/g,'').trim();
const grouped=[{...a,camion:'5',chofer:'Juan'},{...b,camion:'3',chofer:'JUAN RECARGA'}];
assert.equal(ctx.distanceGroups(grouped,'camion').length,2);
assert.equal(ctx.distanceGroups(grouped,'chofer').length,1);
assert.equal(ctx.distanceGroups(grouped,'chofer')[0].plan,15);
assert.equal(ctx.distanceGroups(grouped,'chofer')[0].real,12);
assert.equal(ctx.distanceGroups(grouped.filter(r=>r.camion==='5'),'camion')[0].plan,10);
console.log('Truck and driver breakdown: grouping, driver normalization and filtered totals OK');
const ranked=ctx.fuelRanking(grouped,'camion',1000);
assert.equal(ranked.length,1);
assert.equal(ranked[0].key,'5');
assert.equal(ranked[0].km,12);
assert(Math.abs(ranked[0].real-3.36)<1e-9);
assert(Math.abs(ranked[0].costReal-3360)<1e-9);
assert.equal(ctx.fuelRanking(grouped,'chofer',null)[0].costReal,null);
assert.equal(ctx.fuelRanking([],'camion',1000).length,0);
console.log('Fuel rankings: real kilometers, liters, costs, missing price and empty filters OK');
const histRows=[{...a,fecha:'2026-01-01'},{...a,rid:'c',fecha:'2026-02-01'}];
const histStats=ctx.distanceStats(histRows);
const histFuel=ctx.fuelStats(histStats,{'2026-01-01':1000,'2026-02-01':2000});
assert(Math.abs(histFuel.costReal-10080)<1e-8);
assert(Math.abs(histFuel.costPairPlan-8400)<1e-8);
assert(Math.abs(histFuel.costDiff-1680)<1e-8);
assert.equal(ctx.fuelStats(histStats,{'2026-01-01':1000}).costReal,null);
console.log('Historical fuel: each route uses its own date, missing dates never use current price OK');
const visits=[{rid:'a',cliente:'1',nombre:'One',visitas:3,validas:2,segundos:120},{rid:'c',cliente:'1',nombre:'One',visitas:1,validas:1,segundos:180},{rid:'missing',cliente:'2',visitas:1,validas:1,segundos:900}];
const pdvs=ctx.pdvTimeGroups(visits,[{...a,suc:'A'},{...a,rid:'c',suc:'A'}]);
assert.equal(pdvs.length,1);
assert.equal(pdvs[0].validas,3);
assert.equal(pdvs[0].visitas,4);
assert(Math.abs(pdvs[0].avg-5/3)<1e-9);
assert.equal(ctx.pdvTimeGroups(visits,[{...a,suc:'A'},{...a,rid:'c',suc:'B'}]).length,2);
console.log('PDV times: weighted visits, separate branches and route filters OK');
const segment=ctx.pdvSegmentGroups([{subcanal:'A',visitas:2,validas:1,segundos:600},{subcanal:'A',visitas:9,validas:9,segundos:540}], 'subcanal');
assert.equal(segment[0].pdvs,2);
assert.equal(segment[0].validas,10);
assert.equal(segment[0].avg,1.9);
assert.equal(ctx.pdvSegmentGroups([{validas:0,visitas:1,segundos:0}], 'agrupacion')[0].avg,null);
console.log('Customer segment rankings: visit-weighted means and unclassified coverage OK');
