const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(require('path').join(__dirname,'..','plantilla_dashboard.html'),'utf8');
for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))if(m[1].trim())new vm.Script(m[1]);
assert.ok(!html.includes('id="kOTIF"'));
assert.ok(!html.includes('function otifCalc('));
assert.ok(html.includes('function renderOtif(){renderDocOtif()}'));
assert.ok(html.includes('switchTab(state.tab)'));
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
assert.equal(ids.length,new Set(ids).size,'Duplicate dashboard IDs');
console.log('Dashboard syntax, unique IDs, one OTIF report and direct tab navigation OK');
