const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(require('path').join(__dirname,'..','plantilla_dashboard.html'),'utf8');
for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))if(m[1].trim())new vm.Script(m[1]);
const start=html.indexOf('function otifCalc('),end=html.indexOf('\nfunction ',html.indexOf('function otifMes(',start)+1);
const context={sucNorm:s=>s.toLowerCase()};vm.createContext(context);vm.runInContext(html.slice(start,end),context);
const route=orders=>({rid:'r1',suc:'Central',fecha:'2026-09-01',mes:'2026-09',otif_detalle_completo:true,otif_pedidos:orders});
const order=(id,onTime,complete)=>({pedido_id:id,a_tiempo:onTime,completo:complete});
let result=context.otifCalc([route([order('1',true,true),order('2',false,true),order('3',true,false),order('4',false,false)])]);
assert.equal(result.total,4);assert.equal(result.ok,1);assert.equal(result.no,3);assert.equal(result.otif,25);assert.equal(result.noOtif,75);
result=context.otifCalc([route([order('1',true,true),order('1',true,true)])]);assert.equal(result.total,1);assert.equal(result.otif,100);
result=context.otifCalc([route([order('1',true,true),order('1',false,true)])]);assert.equal(result.unknown,1);assert.equal(result.otif,null);
result=context.otifCalc([route([order('1',null,true)])]);assert.equal(result.otif,null);assert.equal(result.unknown,1);
result=context.otifCalc([route([order('1',true,null)])]);assert.equal(result.otif,null);
result=context.otifCalc([route([order('1',false,null)])]);assert.equal(result.no,1);assert.equal(result.otif,0);
result=context.otifCalc([{pdv_ontime:80,pdv_fuera_ontime:20}], [{rechazos:10,pedidos_pdv_atendidos:100}]);assert.equal(result.otif,null);assert.equal(result.total,null);assert.equal(result.missingRoutes,1);
result=context.otifCalc([], [{rechazos:0,pedidos_pdv_atendidos:100}]);assert.equal(result.otif,null);
result=context.otifCalc([route([order('1',true,true)]),{...route([order('1',true,true)]),rid:'r2',fecha:'2026-09-02'}]);assert.equal(result.otif,null);assert.equal(result.identified,1);
result=context.otifCalc([route([order('1','true','true')])]);assert.equal(result.otif,null);
result=context.otifCalc([route([order('',true,true)])]);assert.equal(result.otif,null);assert.equal(result.unknown,1);
result=context.otifCalc([route([order('1',true,true)]),{...route([]),otif_detalle_completo:false}]);assert.equal(result.otif,null);
const months=context.otifMes([route([order('1',true,true)]),{...route([order('2',false,true)]),mes:'2026-08',fecha:'2026-08-01',rid:'r2'}]);assert.equal(months.length,2);assert.equal(months[0].otif,0);assert.equal(months[1].otif,100);
console.log('OTIF OK: individual outcomes, overlapping failures, duplicates, conflicts, missing evidence, strict booleans and monthly grouping.');
